package view;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import javax.swing.DefaultComboBoxModel;
import config.KoneksiDB;
/**
 * @author ILHAM NA
 */
public class CRUD_Siswa extends javax.swing.JFrame {
 
    public CRUD_Siswa() {
        initComponents();
        tabelSiswa();
        autofillKELAS();
        autofillTAHUN();
        
        BtnUpdate.setEnabled(false);
    }
    
    int _kelas;    
    int _tahun;

    Statement st;
    Connection con = KoneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSiswa = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnRefresh = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        BtnSimpan = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        CBTAHUN = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        TNOTELP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TALAMAT = new javax.swing.JTextField();
        CBKELAS = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TNAMA = new javax.swing.JTextField();
        TNIS = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TNISN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 730));
        setPreferredSize(new java.awt.Dimension(1370, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelSiswa.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        TabelSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelSiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 229, 680, 400));

        cari.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        cari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 500, 30));

        jLabel1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari NISN/Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        BtnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        BtnRefresh.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        BtnRefresh.setForeground(new java.awt.Color(0, 0, 153));
        BtnRefresh.setText("Refresh Table");
        BtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, 130, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 153));
        btnBack.setText("KEMBALI");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 650, 130, -1));

        BtnSimpan.setBackground(new java.awt.Color(0, 0, 153));
        BtnSimpan.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        BtnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        BtnSimpan.setText("Simpan");
        BtnSimpan.setPreferredSize(new java.awt.Dimension(85, 29));
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 609, 100, 40));

        BtnUpdate.setBackground(new java.awt.Color(0, 153, 0));
        BtnUpdate.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Ubah");
        BtnUpdate.setMinimumSize(new java.awt.Dimension(85, 29));
        BtnUpdate.setPreferredSize(new java.awt.Dimension(85, 29));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 609, 100, 40));

        BtnHapus.setBackground(new java.awt.Color(204, 0, 0));
        BtnHapus.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        BtnHapus.setForeground(new java.awt.Color(255, 255, 255));
        BtnHapus.setText("Hapus");
        BtnHapus.setMinimumSize(new java.awt.Dimension(85, 29));
        BtnHapus.setPreferredSize(new java.awt.Dimension(85, 29));
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 609, 100, 40));

        CBTAHUN.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        CBTAHUN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~angkatan tahun" }));
        CBTAHUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTAHUNActionPerformed(evt);
            }
        });
        getContentPane().add(CBTAHUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 230, 40));

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("TAHUN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 90, -1));

        TNOTELP.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        TNOTELP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(TNOTELP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 230, 40));

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("NO TELP");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 90, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("ALAMAT");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 90, -1));

        TALAMAT.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        TALAMAT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(TALAMAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 230, 40));

        CBKELAS.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        CBKELAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~pilih kelas" }));
        CBKELAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBKELASActionPerformed(evt);
            }
        });
        getContentPane().add(CBKELAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 230, 40));

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 80, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Nama Siswa");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 100, -1));

        TNAMA.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        TNAMA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(TNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, 40));

        TNIS.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        TNIS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(TNIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, 40));

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("NIS SMK");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 90, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("NISN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 80, -1));

        TNISN.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        TNISN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(TNISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 230, 40));

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KELOLA DATA SISWA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg-CrudData.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try { 
            String valueKelas = CBKELAS.getSelectedItem().toString();
            String valueTahun = CBTAHUN.getSelectedItem().toString();

            ResultSet rsKelas = con.createStatement().executeQuery("select id_kelas from kelas where nama_kelas='"+valueKelas+"'");
            ResultSet rsTahun = con.createStatement().executeQuery("select id_spp from spp where tahun='"+valueTahun+"'");
            
            while(rsKelas.next()) {
              _kelas = Integer.parseInt(rsKelas.getString("id_kelas"));
            }
            while(rsTahun.next()) {
              _tahun = Integer.parseInt(rsTahun.getString("id_spp"));
            }
            String nis = TNIS.getText();
            String nama = TNAMA.getText();
            String alamat = TALAMAT.getText();
            String telp = TNOTELP.getText();

            con.createStatement().executeUpdate("update siswa set nis='"+nis+"', nama='"+nama+"',id_kelas='"+_kelas+"', alamat='"+alamat+"', no_telp='"+telp+"', id_spp='"+_tahun+"' where nisn='"+model.getValueAt(TabelSiswa.getSelectedRow(),0)+"'");
            JOptionPane.showMessageDialog(this, "Data Berhasil Di Edit");
        }catch (Exception e) {
            System.out.println(e);
        }
        resetForm();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        String nisn = TNISN.getText();
        String nis = TNIS.getText();
        String nama = TNAMA.getText();
        int kelas =  _kelas;
        String alamat = TALAMAT.getText();
        String telp = TNOTELP.getText();
        int tahun =  _tahun;
        
        
        try{ 
           con.createStatement().executeUpdate("insert into siswa value ('"+nisn+"','"+nis+"','"+nama+"','"+kelas+"','"+alamat+"','"+telp+"','"+tahun+"')");
           JOptionPane.showMessageDialog(null, "Data siswa berhasil ditambahkan");
           resetForm();
        }catch (Exception ex) {
            System.out.println(""+ex);
            JOptionPane.showMessageDialog(null, "Gagal!"); 
        }

    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void CBKELASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBKELASActionPerformed
        try { 
          String comboboxIsi = CBKELAS.getSelectedItem().toString();
          rs = con.createStatement().executeQuery("select * from kelas where nama_kelas='"+comboboxIsi+"'");
          while(rs.next()) {
              _kelas = Integer.parseInt(rs.getString("id_kelas"));
          }
        }catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CBKELASActionPerformed

    private void CBTAHUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTAHUNActionPerformed
        try { 
          String comboboxIsi = CBTAHUN.getSelectedItem().toString();
          rs = con.createStatement().executeQuery("select * from spp where tahun='"+comboboxIsi+"'");
          while(rs.next()) {
              _tahun = Integer.parseInt(rs.getString("id_spp"));
          }
        }catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_CBTAHUNActionPerformed

    private void TabelSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelSiswaMouseClicked
        
       int i = TabelSiswa.getSelectedRow();
       TNISN.setText(model.getValueAt(i, 0).toString());
       TNIS.setText(model.getValueAt(i, 1).toString());
       TNAMA.setText(model.getValueAt(i, 2).toString());
       CBKELAS.setSelectedItem(model.getValueAt(i, 3));
       TALAMAT.setText(model.getValueAt(i, 4).toString());
       TNOTELP.setText(model.getValueAt(i, 5).toString());
       CBTAHUN.setSelectedItem(model.getValueAt(i, 6));        
       
//       disabled item on klik row table
       TNISN.setEnabled(false);
       BtnSimpan.setEnabled(false);
       BtnUpdate.setEnabled(true);
    }//GEN-LAST:event_TabelSiswaMouseClicked

    private void cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyPressed
       tabelSiswa();
    }//GEN-LAST:event_cariKeyPressed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        try { 
            con.createStatement().executeUpdate("delete from siswa where nisn ='"+TNISN.getText()+"'");
            JOptionPane.showMessageDialog(null, "berhasil");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "gagal");
        }
        resetForm();
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        tabelSiswa();
    }//GEN-LAST:event_cariKeyReleased

    private void BtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefreshActionPerformed
        resetForm();
        BtnUpdate.setEnabled(false);
        BtnSimpan.setEnabled(true);
    }//GEN-LAST:event_BtnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Dashboard dsb = new Dashboard();
        dsb.dashAdmin();
        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
        dsb.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnRefresh;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CBKELAS;
    private javax.swing.JComboBox<String> CBTAHUN;
    private javax.swing.JTextField TALAMAT;
    private javax.swing.JTextField TNAMA;
    private javax.swing.JTextField TNIS;
    private javax.swing.JTextField TNISN;
    private javax.swing.JTextField TNOTELP;
    private javax.swing.JTable TabelSiswa;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField cari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void tabelSiswa() {
        String[] judul = {"NISN","NIS","Nama","Kelas","Alamat","Telepon","Tahun"};
        model = new DefaultTableModel(judul,0);
        TabelSiswa.setModel(model);
        String sql = "SELECT siswa.*, kelas.nama_kelas, spp.tahun from siswa INNER JOIN kelas USING(id_kelas) INNER JOIN spp Using(id_spp) where nisn like '%"+cari.getText()+"%' or nama like '%"+cari.getText()+"%'";
        
        try {
            rs = con.createStatement().executeQuery(sql);
            
            while(rs.next()) {
               String nisn = rs.getString("nisn");
               String nis = rs.getString("nis");
               String nama = rs.getString("nama");
               String kelas = rs.getString("nama_kelas");
               String alamat = rs.getString("alamat");
               String telp = rs.getString("no_telp");
               String tahun = rs.getString("tahun");
                
               String[] data = {nisn, nis, nama, kelas, alamat, telp, tahun};
               model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    
    }
    
    private void autofillKELAS() {                
       try {
           rs = con.createStatement().executeQuery("select * from kelas");
           while (rs.next()) {
               CBKELAS.addItem(rs.getString("nama_kelas"));
           }         
       } catch (Exception e) {
           System.out.println(e);
       }
    }
    
    private void autofillTAHUN() {                
       try {
           rs = con.createStatement().executeQuery("select * from spp");
           while (rs.next()) {
               CBTAHUN.addItem(rs.getString("tahun"));
           }         
       } catch (Exception e) {
           System.out.println(e);
       }
    }

    public void resetForm(){
        TNISN.setText("");
        TNIS.setText("");
        TNAMA.setText("");
        CBKELAS.setSelectedItem("~pilih kelas");
        TALAMAT.setText("");
        TNOTELP.setText("");
        CBTAHUN.setSelectedItem("~angkatan tahun");
        
        tabelSiswa();
        BtnSimpan.setEnabled(true);
        TNISN.setEnabled(true);
    }
}
