/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import javax.swing.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import config.KoneksiDB;
import config.UserSession;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author ILHAM NA
 */
public class FormTransaksi extends javax.swing.JFrame {

    //get user data session
    String id = UserSession.get_id();
    String nama = UserSession.get_nama();
    String level = UserSession.get_level();
    
    
    public FormTransaksi() {
        initComponents();
        tabelSiswa();

        
//       tNo_Transaki.setText("Auto fill");
       tNo_Transaki.setEnabled(false);
       tTanggal.setEnabled(false);
       tId_Angkatan.setEnabled(false);
       tId_petugas.setEnabled(false);
    }
    
    Statement st;
    Connection con = KoneksiDB.getConnection();
    ResultSet rs;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;
    DefaultTableModel modelStatus;
    Calendar kalender = new GregorianCalendar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSiswa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelStatusBayar = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        tNama_siswa1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tNo_Transaki = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tNisn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tNama_siswa = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tKelas = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tId_Angkatan = new javax.swing.JTextField();
        tPetugas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        tJumlah_bayar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tId_petugas = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        tTanggal = new javax.swing.JTextField();
        tAngkatan = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSAKSI PEMBAYARAN SPP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        cari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cariKeyTyped(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 400, 30));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari siswa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        TabelSiswa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        TabelSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelSiswa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 509, 190));

        tabelStatusBayar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tabelStatusBayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelStatusBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelStatusBayarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabelStatusBayarMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tabelStatusBayar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 509, 170));

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status bayar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        tNama_siswa1.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        tNama_siswa1.setForeground(new java.awt.Color(255, 255, 255));
        tNama_siswa1.setText("~");
        getContentPane().add(tNama_siswa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 380, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("KEMBALI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, -1, 30));

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel2.setText("No.Transaksi   :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        tNo_Transaki.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tNo_Transaki.setText("Trns000");
        getContentPane().add(tNo_Transaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel4.setText("NISN                  :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        tNisn.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tNisn.setText("~");
        tNisn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tNisnPropertyChange(evt);
            }
        });
        getContentPane().add(tNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel6.setText("Nama Siswa    :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        tNama_siswa.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tNama_siswa.setText("~");
        getContentPane().add(tNama_siswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel7.setText("Kelas                 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        tKelas.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tKelas.setText("~");
        getContentPane().add(tKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel5.setText("Angkatan        :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        tId_Angkatan.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        getContentPane().add(tId_Angkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 30, -1));

        tPetugas.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tPetugas.setText("~");
        getContentPane().add(tPetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 100, 20));

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel8.setText("Tanggal");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, -1, 20));

        cbBulan.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "januari", "februari", "maret", "april", "mei", "juni", "juli", "agustus", "september", "oktober", "november", "desember" }));
        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });
        getContentPane().add(cbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 163, -1));

        jLabel11.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel11.setText("Petugas           :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Batalkan");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 100, 30));

        btnSimpan.setBackground(new java.awt.Color(0, 204, 0));
        btnSimpan.setFont(new java.awt.Font("Open Sans ExtraBold", 0, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Bayar");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 100, 30));

        tJumlah_bayar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        getContentPane().add(tJumlah_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 160, -1));

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel10.setText("Bulan");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, -1, -1));

        tId_petugas.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        getContentPane().add(tId_petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 30, -1));

        jLabel14.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel14.setText("Jumlah");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 0, 153));
        jButton7.setText("Reset Form");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 620, 140, 30));

        tTanggal.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        getContentPane().add(tTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 163, -1));

        tAngkatan.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        tAngkatan.setText("~");
        getContentPane().add(tAngkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 90, 20));

        BG.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trans.png"))); // NOI18N
        BG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 7, true));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String no_trans = tNo_Transaki.getText();
        String nisn = tNisn.getText();
        String id_angkatan = tId_Angkatan.getText();
        String id_petugas = tId_petugas.getText();
        String angkatan = tAngkatan.getText();
        String tgl = tTanggal.getText();
        String bln_bayar = cbBulan.getSelectedItem().toString();
        String jml_bayar = tJumlah_bayar.getText();

        try{
            Statement st = con.createStatement();
            String sql = "SELECT * FROM  pembayaran where nisn='"+nisn+"' and bulan_dibayar='"+bln_bayar+"'";
            rs = st.executeQuery(sql);

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Gagal : Transaksi ini sudah dilakukan!");
            } else {
                con.createStatement().executeUpdate("insert into pembayaran value ('"+no_trans+"','"+id_petugas+"','"+nisn+"','"+tgl+"','"+bln_bayar+"','"+angkatan+"','"+id_angkatan+"','"+jml_bayar+"')");
                JOptionPane.showMessageDialog(null, "Berhasil melakukan transaksi");
            }
        }catch (Exception ex) {
            System.out.println(""+ex);
            JOptionPane.showMessageDialog(null, "Gagal!");
        }
        
        tabelStatBayar();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                switch (level) {
                    case "admin":
                    {
                        Dashboard dsb = new Dashboard();
                        dsb.dashAdmin();
                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        dsb.setVisible(true);
                        dispose();
                        break;
                    }
                    case "petugas":
                    {
                        Dashboard dsb = new Dashboard();
                        dsb.dashPetugas();
                        dsb.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        dsb.setVisible(true);
                        dispose();
                        break;
                    }
                    default:
                    break;
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyTyped
        tabelSiswa();
    }//GEN-LAST:event_cariKeyTyped

    private void cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyReleased
        tabelSiswa();
    }//GEN-LAST:event_cariKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       dispose();
       new FormTransaksi().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void TabelSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelSiswaMouseClicked
        ID_AUTO();
        //setting date
        int tahun = kalender.get(Calendar.YEAR);
        int bulan = kalender.get(Calendar.MONTH)+1;
        int hari = kalender.get(Calendar.DAY_OF_MONTH);
        String tanggal = tahun+"/"+bulan+"/"+hari;
        tTanggal.setText(tanggal);
        
        int i = TabelSiswa.getSelectedRow();
        tNisn.setText(model.getValueAt(i, 0).toString());
        tNama_siswa.setText(model.getValueAt(i, 2).toString());
        tNama_siswa1.setText(model.getValueAt(i, 2).toString());
        tKelas.setText(model.getValueAt(i, 3).toString());
        tAngkatan.setText(model.getValueAt(i, 6).toString());
        tId_petugas.setText(id);
        tPetugas.setText(nama);

        try {
            rs = con.createStatement().executeQuery("select siswa.*, spp.* from siswa INNER JOIN spp Using(id_spp)where nisn like '%"+tNisn.getText()+"%'");
            while (rs.next()) {
                tId_Angkatan.setText(rs.getString("id_spp"));
                tJumlah_bayar.setText(rs.getString("nominal"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(false);
        
    }//GEN-LAST:event_TabelSiswaMouseClicked

    private void tNisnPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tNisnPropertyChange
        tabelStatBayar();
    }//GEN-LAST:event_tNisnPropertyChange

    private void tabelStatusBayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelStatusBayarMouseClicked
        int trans = tabelStatusBayar.getSelectedRow();
        tNo_Transaki.setText(modelStatus.getValueAt(trans, 0).toString());
        tTanggal.setText(modelStatus.getValueAt(trans, 1).toString());
        cbBulan.setSelectedItem(modelStatus.getValueAt(trans, 2).toString());
        tJumlah_bayar.setText(modelStatus.getValueAt(trans, 3).toString());

        try {
            rs = con.createStatement().executeQuery("select pembayaran.*, petugas.*, spp.* from pembayaran INNER JOIN petugas Using(id_petugas) INNER JOIN spp Using(id_spp) where id_pembayaran like '%"+tNo_Transaki.getText()+"%'");
            while (rs.next()) {
                tId_Angkatan.setText(rs.getString("id_spp"));
                tAngkatan.setText(rs.getString("tahun"));
                tId_petugas.setText(rs.getString("id_petugas"));
                tPetugas.setText(rs.getString("nama_petugas"));
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tabelStatusBayarMouseClicked

    private void tabelStatusBayarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelStatusBayarMousePressed
        
    }//GEN-LAST:event_tabelStatusBayarMousePressed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            con.createStatement().execute("delete from pembayaran where id_pembayaran='"+tNo_Transaki.getText()+"'");
            JOptionPane.showMessageDialog(null, "Transaksi berhasil dihapus");
            tabelStatBayar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal hapus transaksi");
        }
       
    }//GEN-LAST:event_btnHapusActionPerformed

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBulanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTable TabelSiswa;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel tAngkatan;
    private javax.swing.JTextField tId_Angkatan;
    private javax.swing.JTextField tId_petugas;
    private javax.swing.JTextField tJumlah_bayar;
    private javax.swing.JLabel tKelas;
    private javax.swing.JLabel tNama_siswa;
    private javax.swing.JLabel tNama_siswa1;
    private javax.swing.JLabel tNisn;
    private javax.swing.JLabel tNo_Transaki;
    private javax.swing.JLabel tPetugas;
    private javax.swing.JTextField tTanggal;
    private javax.swing.JTable tabelStatusBayar;
    // End of variables declaration//GEN-END:variables

    private void tabelSiswa() {
        String[] judul = {"NISN","NIS","Nama","Kelas","Alamat","Telepon","Tahun"};
        model = new DefaultTableModel(judul,0);
        TabelSiswa.setModel(model);
        String sql = "SELECT siswa.*, kelas.nama_kelas, spp.tahun from siswa INNER JOIN kelas USING(id_kelas) INNER JOIN spp Using(id_spp) where nisn like '%"+cari.getText()+"%' or nama like '%"+cari.getText()+"%'";
        
        try {
            rs = con.createStatement().executeQuery(sql);
            while(rs.next()) {
               String nisn = rs.getString("nisn");
               String nis = rs.getString("nis");
               String nama = rs.getString("nama");
               String kelas = rs.getString("nama_kelas");
               String alamat = rs.getString("alamat");
               String telp = rs.getString("no_telp");
               String tahun = rs.getString("tahun");
                
               String[] data = {nisn, nis, nama, kelas, alamat, telp, tahun};
               model.addRow(data);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    
    }
    private void tabelStatBayar() {
        String[] header = {"No Transaksi","Tanggal","Bulan","Jumlah Bayar","Status"};
        modelStatus = new DefaultTableModel(header,0);
        tabelStatusBayar.setModel(modelStatus);
        String dataStat = "SELECT * from pembayaran where nisn='"+tNisn.getText()+"'";
        
        try {
            ResultSet queryStat = con.createStatement().executeQuery(dataStat);
            while(queryStat.next()) {
               String no = queryStat.getString("id_pembayaran");
               String tanggal = queryStat.getString("tgl_bayar");
               String bulan = queryStat.getString("bulan_dibayar");
               String jumlah = queryStat.getString("jumlah_bayar");
               String status = "Lunas";
                
               String[] record = {no,tanggal,bulan,jumlah,status};
               modelStatus.addRow(record);
           }
        }catch(Exception e) {
           System.out.println(e);
        }
    }
    
    public void resetForm(){
        tNo_Transaki.setText(""); 
        tId_Angkatan.setText(""); 
        tTanggal.setText(""); 
        tJumlah_bayar.setText(""); 
        tId_petugas.setText(""); 
        tPetugas.setText(""); 
        cbBulan.setSelectedItem("januari");   
        tabelSiswa(); 
    }
        
    /////kode otomatis
    private void ID_AUTO(){
        try {
            String sql="select max(right(id_pembayaran,3)) as no_trans from pembayaran";
            rs = con.createStatement().executeQuery(sql);

            while(rs.next()){
                if(rs.first()==false){
                    tNo_Transaki.setText("TRS001");
                } else{
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                    String nomor=String.valueOf(autoid);
                    
                    for(int a=0;a<3;a++){ 
                        nomor = "0" + nomor;
                    }
                    tNo_Transaki.setText("TRS" + nomor);
                }
            }
        } catch (Exception e) {
            System.out.println("error pembayaran | "+e);
        }
    }

}
